Added HW1 Iterator Class
maltez/react_native_v1 pull request #9
Opened 2019-02-14 12:33 UTC by putchbes

Please review my HW1 and leave yo feedback pozyazya

2019-02-16 16:13 UTC, maltez requested changes

2019-02-16 16:13 UTC, maltez commented on home_work/pavel.ryabinin/hw1/Iterator.js
> +        this[_obj] = obj;
Why you do not use . notation?

2019-02-16 16:13 UTC, maltez commented on home_work/pavel.ryabinin/hw1/Iterator.js
> +             const obj = Object.assign({...this[_obj]}, this);
Reason?

2019-02-16 17:22 UTC, putchbes commented
Because I used Symbol to hide property from Iterator. If use dot.notation -
unnable to create Symbol field.

сб, 16 февр. 2019 г. в 18:13, maltez <notifications@github.com>:

> *@maltez* requested changes on this pull request.
> ------------------------------
>
> In home_work/pavel.ryabinin/hw1/Iterator.js
> <https://github.com/maltez/react_native_v1/pull/9#discussion_r257465936>:
>
> > @@ -0,0 +1,28 @@
> +
> +class Iterator {
> +    constructor(obj) {
> +
> +        this[_obj] = obj;
>
> Why you do not use . notation?
> ------------------------------
>
> In home_work/pavel.ryabinin/hw1/Iterator.js
> <https://github.com/maltez/react_native_v1/pull/9#discussion_r257465971>:
>
> > @@ -0,0 +1,28 @@
> +
> +class Iterator {
> +    constructor(obj) {
> +
> +        this[_obj] = obj;
> +        this.a = 1;
> +        this.b = 2;
> +    }
> +
> +    [Symbol.iterator]() {
> +             let i = -1;
> +             const obj = Object.assign({...this[_obj]}, this);
>
> Reason?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/maltez/react_native_v1/pull/9#pullrequestreview-204524641>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWdY8hmOG5Lfpp3rnVGZxtVab0NF54gCks5vOC4agaJpZM4a7f58>
> .
>

2019-02-25 04:53 UTC, maltez commented on home_work/pavel.ryabinin/hw1/Iterator.js
> +        this[_obj] = obj;
Because .notation shortly and this._obj - do not avoid for error in eslint

2019-04-01 03:11 UTC, maltez approved these changes

2019-04-01 03:11 UTC, merged